<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ragu-PC" ignored="2" name="Default test(failed)" tests="1" failures="1" timestamp="2019-12-20T10:14:24 IST" time="0.101" errors="0">
  <testcase name="divide1" time="0.02" classname="com.testngwork.org.ExceptionTest">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.testngwork.org.ExceptionTest.divide1(ExceptionTest.java:25)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- divide1 -->
  <testcase name="divide" time="0.0" classname="com.testngwork.org.ExceptionTest">
    <ignored/>
  </testcase> <!-- divide -->
  <testcase name="add" time="0.0" classname="com.testngwork.org.ExceptionTest">
    <ignored/>
  </testcase> <!-- add -->
</testsuite> <!-- Default test(failed) -->
